version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    labels:
      - "version-upgrade"
    cooldown:
      default-days: 3

  # npm dependencies
  - package-ecosystem: npm
    directory: ui-super-heroes/src/main/webui
    schedule:
      interval: weekly
    target-branch: main
    labels:
      - "version-upgrade"
      - ui
    cooldown:
      default-days: 7

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "version-upgrade"
    cooldown:
      default-days: 7

